version: '3'
services:
  # nginx:
  #   container_name: nginx-container
  #   build: ./requirements/nginx
  #   ports:
  #     - "3000:90"
  # mariadb:
  #   container_name: mariadb-container
  #   build: ./requirements/mariadb
  #   env_file:
  #     - ./.env
  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress
    env_file:
      - ./.env
    ports:
      - "3000:80"
