version: '3'
services:
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    ports:
      - "8080:8080"
    volumes:
      - "wordpress_data:/var/www/html"
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - "mariadb_data:/var/lib/mysql"
  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_data:/var/www/html"
volumes:
  mariadb_data:
  wordpress_data: